# Generated by Django 5.2.1 on 2025-05-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='sub_linea',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='articulo_condicion',
        ),
        migrations.RemoveField(
            model_name='bonificacion',
            name='articulo_bonificado',
        ),
    ]
