# Generated by Django 5.2.1 on 2025-05-16 23:23

from django.db import migrations, models
import django.db.models.deletion


def transfer_articulos(apps, schema_editor):
    OldArticulo = apps.get_model('core', 'Articulo')
    NewArticulo = apps.get_model('productos', 'Articulo')
    
    for old_articulo in OldArticulo.objects.all():
        NewArticulo.objects.create(
            id=old_articulo.id,
            empresa_id=old_articulo.empresa_id,
            sub_linea_id=old_articulo.sub_linea_id,
            codigo=old_articulo.codigo,
            codigo_barra=old_articulo.codigo_barra,
            nombre=old_articulo.nombre,
            descripcion=old_articulo.descripcion,
            unidad_medida=old_articulo.unidad_medida,
            peso=old_articulo.peso,
            precio=old_articulo.precio,
            stock_minimo=old_articulo.stock_minimo,
            stock_maximo=old_articulo.stock_maximo,
            estado=old_articulo.estado,
            fecha_creacion=old_articulo.fecha_creacion,
            fecha_actualizacion=old_articulo.fecha_actualizacion
        )

def reverse_transfer(apps, schema_editor):
    NewArticulo = apps.get_model('productos', 'Articulo')
    NewArticulo.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_articulo_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('codigo_barra', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock_maximo', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('sub_linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_articulos', to='core.sublineaarticulo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.RunPython(transfer_articulos, reverse_transfer),
    ] 