# Generated by Django 5.2.1 on 2025-05-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pedido_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionpromocion',
            name='canal_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condiciones', to='api.canalcliente'),
        ),
    ]
