# Generated by Django 5.2.1 on 2025-05-31 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_condicionpromocion_canal_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='producto_adicional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_adicionales', to='api.producto'),
        ),
    ]
