# Generated by Django 5.2.1 on 2025-05-16 23:46

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_pedidoitem_articulo_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPromocion',
            fields=[
                ('codigo', models.CharField(choices=[('VOL', 'Volumen'), ('MON', 'Monto')], max_length=3, primary_key=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('cantidad_minima', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_bonificacion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
                ('canal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='core.canalcliente')),
                ('tipo_promocion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promociones.tipopromocion')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ArticuloPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_bonificacion', models.BooleanField(default=False)),
                ('cantidad_bonificacion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='promociones.promocion')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='productos.articulo')),
            ],
            options={
                'verbose_name': 'Artículo en Promoción',
                'verbose_name_plural': 'Artículos en Promoción',
                'unique_together': {('promocion', 'articulo', 'es_bonificacion')},
            },
        ),
    ]
