# Generated by Django 5.2.1 on 2025-05-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0003_promocion_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='activo',
        ),
    ]
