# Generated by Django 5.2.1 on 2025-05-16 23:23

from django.db import migrations, models
import django.db.models.deletion


def disable_foreign_key_checks(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('SET CONSTRAINTS ALL DEFERRED')

def enable_foreign_key_checks(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('SET CONSTRAINTS ALL IMMEDIATE')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_articulo_unique_together_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(disable_foreign_key_checks),
        migrations.RemoveField(
            model_name='bonificacion',
            name='promocion',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='Bonificacion',
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.articulo'),
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.RunPython(enable_foreign_key_checks),
    ]
