# Generated by Django 5.2.1 on 2025-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopromocion',
            name='codigo',
            field=models.CharField(choices=[('VOL', 'Volumen'), ('MON', 'Monto')], max_length=3, primary_key=True, serialize=False),
        ),
    ]
