# Generated by Django 5.2.1 on 2025-05-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0002_alter_tipopromocion_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
